// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAB80V9zf6umD1PeAlN8Hk9HESNAi7MYe8',
    appId: '1:246357426149:web:0ca411c6e68cc52921b90c',
    messagingSenderId: '246357426149',
    projectId: 'jopb-65c0f',
    authDomain: 'jopb-65c0f.firebaseapp.com',
    storageBucket: 'jopb-65c0f.firebasestorage.app',
    measurementId: 'G-3MWQQV3XYJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1mEWVGm55H-lZMyEQa3EgaeZMbqpauSU',
    appId: '1:246357426149:android:a4efcc68aebaa99921b90c',
    messagingSenderId: '246357426149',
    projectId: 'jopb-65c0f',
    storageBucket: 'jopb-65c0f.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnqaE-TxqPS2-ERmdR2dCAB8Ygm3mnc5c',
    appId: '1:246357426149:ios:54bcebff76ebf9e621b90c',
    messagingSenderId: '246357426149',
    projectId: 'jopb-65c0f',
    storageBucket: 'jopb-65c0f.firebasestorage.app',
    androidClientId: '246357426149-ktt86683fge7ecnij2drmdt0c6pa2kek.apps.googleusercontent.com',
    iosClientId: '246357426149-qgncqtch4l3r1pflbrcnri22mo16737j.apps.googleusercontent.com',
    iosBundleId: 'com.jobplanner.jobPlanner',
  );
}
