class AppStrings {
  AppStrings._();

  static const appName = '플루토';
  static const jobGreeting = '오늘도 한 걸음 더';
  static const jobSubtitle = '취업 과정을 한곳에서 관리하세요';
  static const compactView = '간략히 보기';
  static const detailedView = '자세히 보기';
  static const defaultView = '기본보기';
  static const categoryView = '카테고리별 보기';
  static const ledgerKindColorView = '유형 색으로 보기';
  static const settingsTitle = '설정';
  static const settingsAppSection = '앱';
  static const settingsBackupSection = '데이터 설정';
  static const settingsCalendarSyncSection = '캘린더 연동';
  static const importSamsungCalendar = '삼성 캘린더';
  static const importIosCalendar = 'iOS 캘린더';
  static const importComingLaterTitle = '아직 준비 중이에요';
  static const importComingLaterBody = 'iOS 캘린더 연동은 곧 추가될 예정이에요';
  static const importAndroidOnlyTitle = '안드로이드에서 가져올 수 있어요';
  static const importAndroidOnlyBody = '삼성 캘린더 가져오기는 안드로이드 폰에서 사용할 수 있어요';
  static const importIosOnlyTitle = '아이폰에서 가져올 수 있어요';
  static const importIosOnlyBody = 'iOS 캘린더 가져오기는 아이폰에서 사용할 수 있어요';
  static const importPermissionTitle = '캘린더 권한이 필요해요';
  static const importPermissionBody = '기본 캘린더에 있는 일정을 플루토로 가져오려면 권한이 필요해요';
  static const importPermissionSettings = '설정으로 이동';
  static const importCalendarsTitle = '가져올 캘린더';
  static const importCalendarsBody = '선택한 캘린더의 일정을 할 일로 가져와요';
  static String importCalendarEventCount(int count) => '할 일 $count개';
  static const importRangeLabel = '가져올 기간';
  static const importRangeAll = '전체 기간';
  static String importRangeValue(DateTime from, DateTime to) =>
      '${from.year}. ${from.month}. ${from.day}. ~ ${to.year}. ${to.month}. ${to.day}.';
  static const importNoCalendarsTitle = '가져올 캘린더가 없어요';
  static const importNoCalendarsBody = '가져올 수 있는 캘린더가 없어요';
  static const importNoEventsTitle = '가져올 일정이 없어요';
  static const importNoEventsBody = '해당 기간에 새로 가져올 일정이 없어요';
  static const importObservanceSkippedBody = '공휴일과 생일은 할 일로 넣지 않았어요';
  static const importConfirmTitle = '가져올 할 일';
  static String importConfirmBody(int count) => '일정 $count개를 할 일로 가져와요';
  static const importConfirmSkipHint = '가져올 일정만 체크하면 돼요';
  static const importCategoryModeTitle = '카테고리를 어떻게 넣을까요?';
  static const importCategoryAll = '하나에 몰아넣기';
  static const importCategoryAllBody = '모든 일정을 같은 카테고리로 넣어요';
  static const importCategoryEach = '개별로 고르기';
  static const importCategoryEachBody = '할 일마다 카테고리를 고르면 돼요';
  static const importCategoryEachTitle = '할 일별 카테고리';
  static const importCategoryPick = '카테고리 고르기';
  static const importCategoryAllHint = '카테고리를 고르면 모든 할 일에 들어가요';
  static const importCategoryEachHint = '카테고리를 누르면 할 일에 들어가요';
  static const importDoneTitle = '가져오기 성공!';
  static String importDoneBody(int count) => '할 일 $count개를 캘린더에 넣었어요';
  static String importDonePartialBody(int count) =>
      '일정이 많아서 할 일 $count개만 가져왔어요';
  static const importFailedTitle = '가져오지 못했어요';
  static const importFailedBody = '잠시 후 다시 시도해 주세요';
  static const importAction = '가져오기';
  static const importBack = '이전';
  static const importNext = '다음';
  static String importStepLabel(int step, int total) => '$step/$total';
  static const importRangeTitle = '가져올 기간';
  static const importRangeBody = '시작 날과 마지막 날을 고르면 그 사이 일정만 가져와요';
  static const backupData = '데이터 백업하기';
  static const restoreData = '데이터 복구하기';
  static const backupSavedTitle = '백업했어요';
  static const backupSavedBody =
      '구글 드라이브에 저장했어요. 앱을 지워도 백업 파일로 복구할 수 있어요';
  static const backupSavedBodyIos =
      '아이클라우드에 저장했어요. 앱을 지워도 백업 파일로 복구할 수 있어요';
  static const backupFailedTitle = '백업하지 못했어요';
  static const backupFailedBody = '잠시 후 다시 시도해 주세요';
  static const backupIcloudUnavailableBody =
      '아이클라우드에 로그인되어 있는지 확인해 주세요';
  static const backupDriveUnavailableBody =
      '구글 계정에 로그인되어 있는지 확인해 주세요';
  static const restoreConfirmTitle = '데이터를 복구할까요?';
  static const restoreConfirmBody = '지금 있는 데이터가 백업 파일로 바뀌어요';
  static const restorePickOther = '다른 파일 고르기';
  static const restoreNotIcloudBody =
      '플루토 아이클라우드 폴더에 있는 백업만 고를 수 있어요';
  static const restoreLatest = '가장 최근';
  static const restoreAction = '복구하기';
  static const restoreDoneTitle = '복구했어요';
  static const restoreDoneBody = '앱에 데이터가 바로 반영돼요';
  static const restoreFailedTitle = '복구하지 못했어요';
  static const restoreFailedBody = '플루토 백업 파일이 맞는지 확인해 주세요';
  static const autoBackupSetting = '자동저장 주기';
  static const autoBackupDaily = '매일';
  static const autoBackupEvery3Days = '3일마다';
  static const autoBackupWeekly = '일주일마다';
  static const autoBackupMonthly = '한 달마다';
  static String autoBackupHint(String label) => '앱을 켜면 $label 자동으로 저장해요';
  static const appTutorial = '앱 둘러보기';
  static const appContact = '앱 문의하기';
  static const appContactEmail = 'pluto.app.help@gmail.com';
  static const appContactSubject = '플루토 문의';
  static const appContactCopied = '메일 주소를 복사했어요';
  static const tutorialSkip = '건너뛰기';
  static const tutorialPrev = '이전';
  static const tutorialStart = '시작하기';
  static const tutorialNext = '다음';
  static const tutorialDone = '확인';
  static const tutorialBadgeStart = '시작';
  static const tutorialBadgeNav = '탭';
  static const tutorialBadgeCalendar = '캘린더';
  static const tutorialBadgeHome = '홈';
  static const tutorialBadgeJob = '지원서';
  static const tutorialBadgeStats = '통계';
  static const tutorialNavStatsTitle = '통계 화면';
  static const tutorialNavStatsBody =
      '이번 달에 끝낸 할 일로 행성이 성장해요. 상단의 날짜를 누르면 지난달도 볼 수 있어요';
  static const tutorialStatsPlanetTitle = '행성이 성장해요';
  static const tutorialStatsPlanetBody =
      '할 일을 끝낼 때마다 경험치가 쌓여요. 단계가 오르면 행성이 바뀌고, 50개를 끝내면 플루토가 돼요';
  static const tutorialStatsGuideTitle = '행성 도감';
  static const tutorialStatsGuideBody =
      '행성 아래 이름을 누르면 단계를 볼 수 있어요. 내가 모은 행성을 누르면 달마다 모은 행성을 볼 수 있어요';
  static const tutorialStatsDaysTitle = '활동한 날';
  static const tutorialStatsDaysBody =
      '아래 달력에서 할 일을 끝낸 날이 표시돼요. 날짜를 누르면 그날 할 일을 열 수 있어요';
  static const tutorialWelcomeTitle = '플루토에 처음 오셨네요!';
  static const tutorialWelcomeBody = '튜토리얼을 시작할까요?';
  static const tutorialWelcomeBodyDaily = '튜토리얼을 시작할까요?';
  static const tutorialFollow = '따라 해보세요';
  static const tutorialAddTapTitle = '날짜를 눌러 추가';
  static const tutorialAddTapBody = '오늘 칸을 누르면 할 일을 넣을 수 있어요';
  static const tutorialAddComposeTitle = '할 일 추가';
  static const tutorialAddComposeBody = '제목을 적고 밑에서 카테고리를 골라 보세요';
  static const tutorialAddModeTitle = '넣는 날을 고르기';
  static const tutorialAddModeBody =
      '날짜를 누른 뒤 일반·기간·다중·반복 중에서 골라 보세요';
  static const tutorialAddSaveTitle = '저장하기';
  static const tutorialAddSaveBody = '오른쪽 버튼을 눌러 저장할 수 있어요';
  static const tutorialHandleTitle = '밀어서 지우기 · 꾹 눌러 옮기기';
  static const tutorialHandleBody =
      '왼쪽으로 밀면 지울 수 있고, 꾹 눌러 빼면 다른 날로 옮겨요';
  static const tutorialMoreTitle = '더 많은 기능';
  static const tutorialMoreBody =
      '오른쪽 ··· 을 누르면 일기·가계부로 바꿀 수 있어요. 그 밖에 정렬 방식 등의 여러 기능이 있어요';
  static const tutorialHomeGoTitle = '홈 화면';
  static const tutorialHomeGoBody = '오늘·내일 할 일을 한눈에 볼 수 있어요';
  static const tutorialSettingsTitle = '설정';
  static const tutorialSettingsBody =
      '테마·글꼴·알림 등 다양한 기능으로 나만의 캘린더를 만들 수 있어요';
  static const tutorialStatsGoTitle = '행성이 성장해요';
  static const tutorialStatsGoBody =
      '할 일을 끝내면 행성이 성장해요. 이번 달 얼마나 했는지 한눈에 볼 수 있어요';
  static const tutorialJobGoTitle = '지원서 화면';
  static const tutorialJobGoBody = '아래 지원서를 누르면 회사 카드를 모을 수 있어요';
  static const tutorialJobAddFollowBody = '아래 + 를 누르면 지원서를 넣을 수 있어요';
  static const tutorialNavBarTitle = '아래 탭으로 이동';
  static const tutorialNavBarBody =
      '왼쪽부터 홈, 캘린더, 통계예요. 취준 모드를 켜면 지원서가 통계 앞에 생겨요';
  static const tutorialNavBarBodyDaily =
      '왼쪽부터 홈, 캘린더, 통계예요. 하단 버튼을 눌러 화면을 이동해요';
  static const tutorialNavBarBodyNoStats =
      '왼쪽부터 홈, 캘린더예요. 취준 모드를 켜면 지원서도 생겨요';
  static const tutorialNavBarBodyNoStatsDaily =
      '왼쪽부터 홈, 캘린더예요. 하단 버튼을 눌러 화면을 이동해요';
  static const tutorialNavCalendarTitle = '캘린더 화면';
  static const tutorialNavCalendarBody =
      '지금 있는 화면이 캘린더예요. 할 일과 지원서 일정이 날짜에 라벨로 보여요';
  static const tutorialNavCalendarBodyDaily =
      '지금 있는 화면이 캘린더예요. 할 일이 날짜에 라벨로 보여요';
  static const tutorialCalendarTitleTitle = '달·연도 고르기';
  static const tutorialCalendarTitleBody =
      '월 이름을 누르면 달을 고르고, 한 번 더 누르면 연도를 고를 수 있어요';
  static const tutorialCalendarGridTitle = '날짜를 눌러 추가';
  static const tutorialCalendarGridBody =
      '날짜를 누르면 그날 할 일을 넣거나, 이미 있는 일정을 볼 수 있어요';
  static const tutorialCalendarRangeTitle = '여러 날을 밀어 기간 추가';
  static const tutorialCalendarRangeBody =
      '날짜를 길게 누른 뒤 옆으로 밀면 기간 할 일을 만들 수 있어요';
  static const tutorialCalendarCompleteTitle = '할 일 완료하기';
  static const tutorialCalendarCompleteBody =
      '날짜를 눌러 열린 창에서 동그라미를 누르면 완료예요. 길게 누르면 순서를 바꿀 수 있어요';
  static const tutorialCalendarMoveTitle = '다른 날로 옮기기';
  static const tutorialCalendarMoveBody =
      '열린 창에서 할 일을 밖으로 빼면 다른 날짜로 옮겨요';
  static const tutorialCalendarMenuTitle = '표시 바꾸기';
  static const tutorialCalendarMenuBody =
      '오른쪽 ··· 을 누르면 메뉴가 열려요. 할 일·지원서만 보거나 일기·가계부로 바꿀 수 있어요. 바꾼 뒤 날짜를 누르면 그날 기록을 보거나 추가해요';
  static const tutorialCalendarMenuBodyDaily =
      '오른쪽 ··· 을 누르면 메뉴가 열려요. 할 일만 보거나 일기·가계부로 바꿀 수 있어요. 바꾼 뒤 날짜를 누르면 그날 기록을 보거나 추가해요';
  static const tutorialNavHomeTitle = '홈 화면';
  static const tutorialNavHomeBody =
      '기본으로 오늘·내일 할 일이 보여요. 끝나지 않은 할 일이 있으면 위에 미완료 카드도 생겨요';
  static const tutorialHomeToolsTitle = '위쪽 버튼';
  static const tutorialHomeToolsBody = '돋보기와 설정 버튼이에요';
  static const tutorialHomeSearchTitle = '전체 일정 찾기';
  static const tutorialHomeSearchBody =
      '돋보기를 누르면 할 일과 지원서를 한곳에서 찾아요. 기간을 정하거나 할 일·지원서만 볼 수 있어요';
  static const tutorialHomeSearchBodyDaily =
      '돋보기를 누르면 할 일을 한곳에서 찾아요. 기간을 정하거나 할 일만 볼 수 있어요';
  static const tutorialHomeSettingsTitle = '설정에서 바꾸기';
  static const tutorialHomeSettingsBody =
      '테마·글꼴·알림뿐 아니라 홈에 보여줄 카드, 취준 모드, 백업까지 설정에서 바꿀 수 있어요';
  static const tutorialHomeListTitle = '할 일 카드';
  static const tutorialHomeListBody =
      '오늘·내일 카드예요. 눌러 열고, 길게 눌러 순서를 바꿀 수 있어요';
  static const tutorialNavJobTitle = '지원서 화면';
  static const tutorialNavJobBody =
      '지원 중인 회사가 카드로 모여 있어요. 카드를 눌러 전형과 자기소개서를 관리해요';
  static const tutorialJobToolsTitle = '위쪽 버튼';
  static const tutorialJobToolsBody =
      '돋보기와 오른쪽 메뉴예요. 메뉴에서 자격증으로 바꿀 수 있어요';
  static const tutorialJobAddTitle = '지원서 추가';
  static const tutorialJobAddBody =
      '아래 + 로 지원서를 넣고, 카드를 밀어 순서를 바꾸고, 왼쪽으로 밀면 지울 수 있어요';
  static const tutorialDoneTitle = '이제 시작할 수 있어요';
  static const tutorialDoneBody = '설정 > 앱 둘러보기에서 언제든 다시 볼 수 있어요';
  static const starterTodoComplete = '오른쪽 동그라미를 눌러 완료할 수 있어요';
  static const starterTodoReorder = '꾹 눌러서 위치를 바꿀 수 있어요';
  static const starterTodoMove = '밖으로 빼서 날짜를 옮길 수 있어요';
  static const releaseNotesTitle = '릴리즈 노트';
  static const accountTitle = '로그인하기';
  static const accountLogin = '로그인하기';
  static const accountLogout = '로그아웃하기';
  static const accountDelete = '탈퇴하기';
  static const accountDeleteTitle = '계정을 탈퇴할까요?';
  static String accountDeleteBody(String provider) =>
      '해당 $provider 계정이 삭제돼요';
  static const accountDeleteLocalTitle = '이 기기 내용도 지울까요?';
  static const accountDeleteLocalBody =
      '계정에 저장된 내용은 사라져요. 이 기기에 있는 데이터는 남기거나 지울 수 있어요';
  static const accountDeleteKeepLocal = '이 기기 내용은 남길게요';
  static const accountDeleteResetLocal = '이 기기 내용도 지울게요';
  static const accountLogoutDoneTitle = '로그아웃했어요';
  static String accountLogoutDoneBody(String provider) =>
      '$provider 계정에서 로그아웃했어요';
  static const accountDeleteFailedTitle = '탈퇴하지 못했어요';
  static const accountSignedIn = '로그인됨';
  static const accountLoginBody =
      '언제 어디서든 다른 기기와 연동할 수 있어요';
  static const accountLoginPcHint = 'PC에서는 pluto.day 로 열 수 있어요';
  static const featureIntroBanner = '로그인하고 더 많은 기능 보기';
  static const featureIntroTitle = '로그인하면 쓸 수 있어요';
  static const featureIntroClose = '닫기';
  static const featureIntroPcTitle = 'PC 버전';
  static const featureIntroPcBody = 'PC에서도 플루토를 이용할 수 있어요';
  static const featureIntroSyncTitle = '계정 동기화';
  static const featureIntroSyncBody = '데이터를 따로 백업할 필요가 없어요';
  static const featureIntroAiTitle = 'AI 카테고리';
  static const featureIntroAiBody = 'AI가 할 일에 따라 카테고리를 자동으로 골라줘요';
  static const featureIntroAiThinking = '고르는 중';
  static const featureIntroAiPicked = '운동으로 집어 두었어요';
  static const featureIntroFriendsTitle = '친구 추가';
  static const featureIntroFriendsBody = '친구 일정을 보고, 서로 공유하는 할 일을 만들 수 있어요';
  static const featureIntroFriendRequest = '친구 요청';
  static const featureIntroFriendDecline = '거절';
  static const featureIntroFriendAccept = '수락';
  static const featureIntroFriendDone = '친구가 되었어요';
  static const webLoginBrand = '플루토';
  static const webLoginTagline = '오직 나만의 캘린더';
  static const webLoginPcLabel = 'PC버전';
  static const accountLoginWebUrl = 'pluto.day';
  static const accountLoginSocialHint = '소셜 계정으로 로그인';
  static const accountKakaoShort = '카카오톡';
  static const accountGoogleShort = 'Google';
  static const accountAppleShort = 'Apple';
  static const accountFailedTitle = '로그인하지 못했어요';
  static const accountFailedBody = '잠시 후 다시 시도해 주세요';
  static const accountKakaoKeyBody = '카카오 로그인은 아직 준비 중이에요';
  static const accountKakaoWebKeyBody =
      '카카오 디벨로퍼스 앱 키에서 JavaScript 키를 넣어 주세요';
  static const accountKakaoOidcBody = '카카오 계정 연결이 아직 끝나지 않았어요';
  static const accountKakaoMisconfiguredBody =
      '카카오 디벨로퍼스에서 네이티브 앱 키의 패키지명과 키 해시를 확인해 주세요';
  static const accountKakaoWebMisconfiguredBody =
      '카카오 디벨로퍼스 Web 플랫폼에 이 사이트 주소(예: https://pluto.day)를 등록해 주세요';
  static const accountKakaoWebAudBody =
      'Firebase 인증 > OpenID Connect(kakao)의 Client ID를 아래 JavaScript 키로 바꿔 주세요';
  static const accountUnavailableBody = '지금은 로그인을 사용할 수 없어요';
  static const accountSyncFailedBody = '계정 내용을 불러오지 못했어요. 인터넷 연결을 확인해 주세요';
  static const accountLogoutSyncBody =
      '계정에 올리는 중이어서 지금은 로그아웃할 수 없어요. 잠시 후 다시 시도해 주세요';
  static const releaseNotesFeatures = '새로운 기능';
  static const releaseNotesFixes = '버그 수정';
  static const releaseNotesPreview = '이렇게 바뀌었어요';
  static const settingsHomeSection = '홈 화면';
  static const settingsHomeLayoutSection = '홈 화면 설정';
  static const homeShowFriends = '친구';
  static const homeShowLeftover = '미완료 할 일';
  static const homeShowMemo = '메모';
  static const homeShowToday = '오늘';
  static const homeShowTomorrow = '내일';
  static const homeShowWeek = '이번 주';
  static const homeShowMonth = '이번 달';
  static const homeShowSomeday = '언젠가';
  static const homeShowLongGoal = '챌린지';
  static const somedayTitle = '언젠가';
  static const homePickCards = '보여줄 카드';
  static const homeReorderCards = '순서 바꾸기';
  static const memoTitle = '메모';
  static const memoAdd = '+ 메모를 추가하세요';
  static const memoTitleHint = '제목을 입력하세요';
  static const memoBodyHint = '메모를 입력하세요';
  static const memoMissingTitle = '제목은 필수사항이에요!';
  static const memoDeleteBody = '메모가 사라져요';
  static const longGoalTitle = '챌린지';
  static const longGoalAdd = '+ 할 일을 추가하세요';
  static const longGoalNameHint = '할 일을 입력하세요';
  static const longGoalUnitHint = '단위';
  static const longGoalTargetHint = '목표치';
  static const longGoalMissingName = '할 일은 필수사항이에요!';
  static const longGoalMissingTarget = '목표치는 필수사항이에요!';
  static const longGoalMissingCategory = '카테고리는 필수사항이에요!';
  static const longGoalKindMeasure = '수치';
  static const longGoalKindSum = '쌓기';
  static const longGoalKindDaily = '매일';
  static const longGoalKindStreak = '연속';
  static const longGoalKindMeasureHint = '다이어트, 점수처럼 오늘의 값을 적어요';
  static const longGoalKindSumHint = '총 시간, 총 권수처럼 한 양을 더해요';
  static const longGoalKindDailyHint = '매일 독서, 매일 운동처럼 했는지 기록해요';
  static const longGoalKindStreakHint = '하루라도 빠지면 처음부터 다시해요';
  static const longGoalKindAction = '분류';
  static const longGoalNotLogged = '오늘 미기록';
  static const longGoalTodayLog = '오늘의 기록';
  static const longGoalTodayValueHint = '오늘 값';
  static const longGoalTodayAmountHint = '오늘 한 양';
  static const longGoalValueHint = '값';
  static const longGoalAmountHint = '한 양';
  static const longGoalToday = '오늘';
  static const longGoalCheckInDone = '완료';
  static const longGoalRestart = '다시 시작하기';
  static const longGoalProgress = '진척도';
  static const longGoalRecent = '최근 기록';
  static const longGoalEmptyHistory = '아직 기록이 없어요';
  static const longGoalDeleteBody = '챌린지와 기록이 사라져요';
  static String longGoalPercent(int value) => '$value%';
  static const settingsMonthlyStatsSection = '통계 알림';
  static const homeShowMonthlyStats = '지난달 요약';
  static const homeShowWeeklyStats = '지난주 요약';
  static const settingsTodoSection = '할 일 설정';
  static const settingsCategorySection = '카테고리 설정';
  static const settingsCategoryHelp =
      '제목을 입력하면 AI가 알맞는 카테고리를 선택해요';
  static const settingsAppearanceSection = '화면 모드';
  static const settingsNavSection = '하단 메뉴 설정';
  static const jobMode = '취준 모드';
  static const statsTab = '통계';
  static const settingsNavHelp =
      '취준 모드로 지원서·자격증 메뉴를 켜거나, 통계 탭을 끌 수 있어요';
  static const settingsThemeSection = '테마 설정';
  static const themeKind = '테마 종류';
  static const themeGroupPattern = '패턴';
  static const themeGroupScene = '이미지';
  static const themeGroupMine = '내 테마';
  static const themeMineCreate = '테마 만들기';
  static const themeMineFullPreview = '전체 보기';
  static const starterThemeReorder = '꾹 눌러서 위치를 바꿀 수 있어요';
  static const starterThemeSwipe = '왼쪽으로 밀어서 수정 및 삭제를 할 수 있어요';
  static const themeMineEdit = '테마 수정';
  static const themeMineNameHint = '테마 이름을 입력하세요';
  static const themeMineAccent = '테마색';
  static const themeMineKindPhoto = '이미지';
  static const themeMineKindPattern = '패턴';
  static const themeMinePhoto = '이미지';
  static const themeMinePhotoWash = '투명도';
  static const themeMineDecoration = '장식';
  static const themeMineDecorationHint = '512×512 정사각, 투명 배경이 좋아요';
  static const themeMineBottom = '하단';
  static const themeMineBottomHint = '2000×600처럼 가로로 긴 사진이 좋아요';
  static const themeMinePatternToast = '장식은 투명 배경, 하단은 가로로 긴 사진이 좋아요';
  static const themeMinePickImage = '사진을 고르세요';
  static const themeMineMissingName = '테마 이름을 입력해 주세요';
  static const themeMineDeleteBody = '만든 테마가 사라져요';
  static const themeClassic = '기본';
  static const themeBlossom = '블라썸';
  static const themeClover = '네잎클로버';
  static const themeFluffyBear = '몽글곰도리';
  static const themeFluffyRabbit = '몽글토끼';
  static const themePinkHeart = '핑크하트';
  static const themeSummerBeach = '한여름 바닷가';
  static const themeSnowyWinter = '눈 내리는 겨울';
  static const themeSquishyBear = '말랑곰탱이';
  static const themeStrawberryMilk = '딸기우유';
  static const themeLovelyBear = '러블리베어';
  static const themeRainyDay = '비와 같이 폴짝';
  static const themeConcertDay = '공연하는 날';
  static const themeFluffyCloud = '몽실구름';
  static const themeCatVillage = '고양이 마을';
  static const themeHamsterBakery = '햄스터 빵집';
  static const themeOtterBathhouse = '아기 수달 목욕탕';
  static const themeRabbitFlowerMarket = '꽃집 토끼들';
  static const themeBearPancakeCafe = '곰돌이 팬케이크';
  static const settingsFontSection = '폰트 설정';
  static const settingsWidgetSection = '위젯 설정';
  static const widgetFollowTheme = '테마 동기화';
  static const widgetFollowFont = '폰트 동기화';
  static const widgetFontSize = '위젯 폰트 크기';
  static const settingsWidgetHelp =
      '위젯이 앱의 테마나 폰트를 따라가게 하거나, 위젯의 글자 크기를 바꿀 수 있어요.';
  static const fontFamily = '폰트 종류';
  static const fontTodoSize = '할 일·지원서 크기';
  static const fontCalendarSize = '캘린더 크기';
  static const fontCalendarLabelSize = '캘린더 라벨 크기';
  static const fontLabelScale = '할 일 폰트 크기';
  static const fontCalendarDateScale = '날짜 폰트 크기';
  static const fontCalendarChipScale = '캘린더 폰트 크기';
  static const fontPretendard = '프리텐다드';
  static const fontPaperlogy = '페이퍼로지';
  static const fontSuit = '수트';
  static const fontTheJamsil = '더잠실체';
  static const fontSystem = '기기 기본';
  static const fontGothic = '고딕';
  static const fontSerif = '명조';
  static const fontOwnglyph = '박다현체';
  static const fontMeetme = '밑미';
  static const fontLeeSeoyoon = '이서윤체';
  static const fontBandal = '반달체';
  static const fontMona = '모나체';
  static const fontOmyu = '오뮤체';
  static const fontBazzi = '배찌체';
  static const fontMabinogi = '마비노기체';
  static const fontBabyShark = '아기상어체';
  static const fontCookieRun = '쿠키런체';
  static const fontSizeSmall = '작게';
  static const fontSizeMedium = '보통';
  static const fontSizeLarge = '크게';
  static const fontSizeExtraLarge = '더 크게';
  static const settingsFontHelp = '앱에 쓰는 글꼴과, 할 일·캘린더 날짜·라벨의 크기를 바꿀 수 있어요';
  static const settingsCalendarSection = '캘린더 설정';
  static const calendarStartMonday = '월요일부터 시작';
  static const calendarShowLunar = '음력 날짜 표시';
  static const settingsHelpPreview = '미리보기';
  static const settingsHomeLayoutHelp =
      '홈 화면에 보여줄 카드를 고르고, 홈에서 카드를 길게 눌러 순서를 바꿀 수 있어요';
  static const settingsTodoHelpSort =
      '시작 시간이 있는 할 일을 빠른 시간부터 줄 세워요. 켜 두면 손으로 순서를 바꿀 수 없어요';
  static const settingsTodoHelpTime = '할 일 라벨에 시작 시간을 보여 줘요';
  static const settingsTodoHelpHour24 =
      '16:00처럼 24시간으로 볼지, 오후 4:00처럼 볼지 골라요. 시간 표시가 켜져 있을 때만 나와요';
  static const settingsTodoHelpCategory = '같은 칸의 할 일을 묶어서 보여 줘요';
  static const settingsTodoHelpParse =
      '제목에 4시나 14시, 오후 4시처럼 적으면 저장할 때 그 글자를 빼고 시간에 넣어요';
  static const settingsNotificationHelp =
      '시간이 있는 할 일은 미리 알려주고, 매일 정해진 시간에 오늘 일정과 끝내지 않은 할 일을 알려줘요';
  static const settingsAppearanceHelp = '화면을 밝은 테마나 어두운 테마로 바꿀 수 있어요';
  static const settingsThemeHelp = '앱의 배경 분위기와 아이콘·버튼 색을 바꿀 수 있어요';
  static const settingsBackupHelp =
      '앱의 모든 데이터를 최근 3개까지 저장해요. 앱을 지운 뒤에도 복구할 수 있어요';
  static const settingsCalendarSyncHelp =
      '기본 캘린더에 있는 일정을 플루토의 캘린더로 가져와요. 가져올 기간을 고르고, 카테고리는 하나에 몰아넣거나 할 일마다 고를 수 있어요.';
  static const settingsAppHelp =
      '릴리즈 노트에서 업데이트 내역을 읽고, 앱 사용법을 보거나, 문의 메일을 보내거나, 로그인·탈퇴할 수 있어요';
  static const settingsCalendarHelp = '캘린더의 첫 요일과 음력 날짜를 표시할 수 있어요';
  static const settingsCalendarHelpWithFontSize =
      '캘린더의 첫 요일과 음력 날짜, 할 일·지원서·날짜·라벨의 글자 크기를 바꿀 수 있어요';
  static const calendarStartSunday = '일요일부터 시작';
  static const settingsMonthlyStatsHelp =
      '매달 1일에는 지난달 요약을, 매주 월요일에는 지난주 요약을 보여줘요';
  static const lightMode = '라이트 모드';
  static const darkMode = '다크 모드';
  static const settingsNotificationSection = '알림 설정';
  static const todoNotificationSetting = '할 일 알림 설정';
  static const summaryNotificationSetting = '요약 알림 설정';
  static const leftoverNotificationSetting = '미완료 할 일';
  static const notifyOff = '사용 안함';
  static const notifyMinutes5 = '5분 전';
  static const notifyMinutes10 = '10분 전';
  static const notifyMinutes30 = '30분 전';
  static const notifyHours1 = '1시간 전';
  static const todoReminderChannelName = '할 일 알림';
  static const todoReminderChannelDescription = '시간이 있는 할 일을 미리 알려줘요';
  static const summaryReminderChannelName = '요약 알림';
  static const summaryReminderChannelDescription = '하루 일정을 모아서 알려줘요';
  static const leftoverReminderChannelName = '미완료 할 일';
  static const leftoverReminderChannelDescription = '그날 끝내지 않은 할 일을 알려줘요';
  static String todoReminderHint(String leadLabel) =>
      '시간이 설정된 할 일을 $leadLabel에 알려줘요';
  static String todoReminderBody(int leadMinutes) => leadMinutes % 60 == 0
      ? '${leadMinutes ~/ 60}시간 후 시작해요'
      : '$leadMinutes분 후 시작해요';
  static String summaryTimeLabel(int minutes) {
    final hour = minutes ~/ 60;
    final minute = minutes % 60;
    final period = hour < 12 ? amLabel : pmLabel;
    final hour12 = hour % 12 == 0 ? 12 : hour % 12;
    return '$period $hour12:${minute.toString().padLeft(2, '0')}';
  }

  static String summaryReminderHint(int minutes) =>
      '매일 ${summaryTimeLabel(minutes)}에 오늘 일정을 알려줘요';
  static String summaryNotificationTitle(int count) =>
      count == 0 ? '오늘의 일정' : '오늘의 일정이 $count개 있어요';
  static const summaryNotificationEmpty = '오늘 일정이 없어요';
  static String leftoverReminderHint(int minutes) =>
      '매일 ${summaryTimeLabel(minutes)}에 완료되지 않은 할 일을 알려줘요';
  static String leftoverNotificationTitle(int count) => '완료되지 않은 할일이 $count개 있어요';
  static const tomorrowNotificationEmpty = '내일 일정이 없어요';
  static const todayTomorrowNotificationEmpty = '오늘과 내일 일정이 없어요';
  static const weekNotificationEmpty = '이번 주 일정이 없어요';
  static const monthNotificationEmpty = '이번 달 일정이 없어요';
  static const companySection = '지원서';
  static const jobScreenTitle = '지원서';
  static const searchHint = '지원서, 카테고리, 분야 검색';
  static const licenseScreenTitle = '자격증';
  static const licenseMode = '자격증 전환';
  static const licenseSearchHint = '자격증, 카테고리, 발급기관 검색';
  static const addLicense = '+ 자격증을 추가하세요';
  static const licenseNameHint = '자격증 이름을 입력하세요';
  static const licenseIssuerHint = '발급기관';
  static const licenseNumberHint = '등록번호';
  static const licenseGradeHint = '점수';
  static const licenseAcquired = '취득일';
  static const licenseExpires = '만료일';
  static const licenseExpired = '만료';
  static const licenseVisibleItems = '자격증에 표시할 항목';
  static const licenseShowExpired = '만료된 자격증';
  static const missingLicenseBody = '자격증과 카테고리는 필수사항이에요!';
  static const deleteLicenseBody = '자격증이 사라져요';
  static const deleteCategoryWithLicenses = '해당하는 자격증도 같이 삭제';
  static const expiredReorderLockBody = '만료된 자격증은 순서를 바꿀 수 없어요';
  static const categoryViewLockBody = '카테고리별 보기가 켜져 있어요!';
  static const homeSearchHint = '할 일, 지원서, 카테고리 검색';
  static const homeSearchHintDaily = '할 일, 카테고리 검색';
  static const addCompany = '+ 지원서를 추가하세요';
  static const addCompanyTitle = '지원서 추가';
  static const save = '저장';
  static const missingFieldsTitle = '무언가 빠뜨렸어요 😭';
  static const missingFieldsBody = '지원서와 카테고리는 필수사항이에요!';
  static const confirm = '확인했어요';
  static const deleteTitle = '정말 삭제할까요?';
  static const deleteBody = '정보가 사라져요';
  static const deleteEventBody = '일정이 사라져요';
  static const deleteCategoryBody = '카테고리가 사라져요';
  static const deleteCategoryOnly = '카테고리만 삭제';
  static const deleteCategoryWithItems = '해당하는 할 일도 같이 삭제';
  static const deleteCategoryWithApplications = '해당하는 지원서도 같이 삭제';
  static const deleteCategoryWithLedgers = '해당하는 내역도 같이 삭제';
  static const deleteCompanyBody = '지원서가 사라져요';
  static const deleteCoverLetterTitle = '자소서를 삭제하시나요?';
  static const deleteCoverLetterBody = '파일이 사라져요';
  static const deleteLicenseFileTitle = '자격증 파일을 삭제하시나요?';
  static const cancel = '취소';
  static const delete = '삭제';
  static const companyNameHint = '지원서를 입력하세요';
  static const colCompany = '지원서';
  static const colApplyStatus = '지원상태';
  static const colPosition = '분야';
  static const positionHint = '분야를 입력하세요';
  static const roundStageNameHint = '전형을 입력하세요';
  static const roundDateHint = '날짜를 입력하세요';
  static const roundChipLabel = '일정';
  static const roundNoteHint = '추가정보를 입력하세요';
  static const emptyValue = '—';
  static const colCoverLetter = '자기소개서';
  static const attachFile = '자기소개서';
  static const attachLicenseFile = '자격증';
  static const coverLetterNotFound = '자기소개서 파일을 찾을 수 없어요';
  static const coverLetterOpenFailed = '파일을 열 수 없어요';
  static const licenseFileNotFound = '자격증 파일을 찾을 수 없어요';
  static const monthSuffix = '월';
  static const yearSuffix = '년';
  static const daySuffix = '일';
  static const weekdays = ['일', '월', '화', '수', '목', '금', '토'];
  static const weekdaysMondayFirst = ['월', '화', '수', '목', '금', '토', '일'];

  static List<String> weekdayLabels({required bool startMonday}) {
    return startMonday ? weekdaysMondayFirst : weekdays;
  }

  static const todayTitle = '오늘';
  static const tomorrowTitle = '내일';
  static const todayTomorrowTitle = '오늘과 내일';
  static const dayAfterTomorrowTitle = '모레';
  static const weekTitle = '이번 주';
  static const monthTitle = '이번 달';
  static const timeMachineNow = '현재';
  static String leftoverTodos(int count) => '$count개의 남은 할 일';
  static const leftoverHeadline = '아직 남은 할 일이';
  static String leftoverCount(int count) => '$count개';
  static const leftoverTail = '있어요';
  static const allEventsCard = '전체 일정 보기';
  static const allEventsTitle = '전체 일정';
  static const allEventsSearchHint = '할 일, 지원서, 카테고리 검색';
  static const allEventsSearchHintDaily = '할 일, 카테고리 검색';
  static const allEventsEmpty = '할 일이 없어요';
  static const allEventsSearchEmpty = '검색 결과가 없어요';
  static const allEventsDeleteAll = '전체 삭제';
  static const searchSortOldest = '날짜 오름차순';
  static const searchDateView = '날짜별 보기';
  static const searchVisibleItems = '검색에 표시할 항목';
  static const searchRangeSetting = '기간 설정';
  static String allEventsDeleteBody(int count) => '할 일 $count개가 사라져요';
  static String monthlyStatsCardTitle(int month) => '$month월 통계가 도착했어요';
  static const weeklyStatsCardTitle = '지난주 통계가 도착했어요';
  static String monthlyStatsHeadlineMonth(int month) => '$month월에는';
  static const weeklyStatsHeadline = '지난주에는';
  static String monthlyStatsTodoCount(int count) => '할 일 $count개';
  static String monthlyStatsRoundCount(int count) => '전형 $count개';
  static const monthlyStatsCompleteAnd = '를 완료하고';
  static const monthlyStatsCompletedTail = '를 완료했어요';
  static const monthlyStatsTotalTail = '가 있었어요';
  static const monthlyStatsRoundsTail = '가 있었어요';
  static const monthlyStatsAnd = '와';
  static const monthlyStatsEmptyTail = '기록이 없어요';
  static const statsPlanetEmpty = '할 일을 완료하면 경험치가 쌓여요';
  static const statsPlanetFilling = '할 일을 끝낼수록 행성이 채워져요';
  static const statsPlanetFull = '이번 달, 플루토가 됐어요';
  static String statsPlanetLeft(int count) => '$count개 남았어요';
  static const statsRank1 = '잠든 행성';
  static const statsRank2 = '깨어난 행성';
  static const statsRank3 = '새벽 행성';
  static const statsRank4 = '분홍 행성';
  static const statsRank5 = '노을 행성';
  static const statsRank6 = '구름 행성';
  static const statsRank7 = '금빛 행성';
  static const statsRank8 = '고리 행성';
  static const statsRank9 = '달';
  static const statsRank10 = '플루토';
  static const statsLevelGuideTitle = '행성 도감';
  static const statsLevelGuideBody = '할 일을 끝낼수록 플루토에 가까워져요';
  static const statsCollectedTitle = '내가 모은 행성';
  static const statsCollectedBody = '플루토와 함께한 여정을 확인할 수 있어요';
  static const statsCollectedEmpty = '할 일을 완료한 달의 행성이 모여요';
  static const statsCollectedYearEmpty = '이 해에 모은 행성이 없어요';
  static String statsCollectedMonth(DateTime month, {required int nowYear}) {
    if (month.year == nowYear) return '${month.month}$monthSuffix';
    return '${month.year}$yearSuffix ${month.month}$monthSuffix';
  }
  static const statsLevelStart = '시작';
  static String statsLevelNeed(int count) => '할 일 $count개';
  static String statsPlanetStage(int stage) => '$stage단계';
  static String statsNextPlanetTodos(int count) => '다음 행성까지 할 일 $count개';
  static const statsCategoriesUsed = '사용한 카테고리';
  static const statsLeftShort = '남은 일';
  static const statsMonthTodos = '이번 달 할 일';
  static const statsActiveDays = '활동한 날';
  static const statsQuests = '이번 달 퀘스트';
  static const statsNoQuests = '할 일을 넣으면 퀘스트가 생겨요';
  static const monthlyStatsCompletedLabel = '완료한 할 일';
  static const monthlyStatsIncompleteLabel = '남은 할 일';
  static const monthlyStatsTotalLabel = '전체 할 일';
  static const monthlyStatsRateLabel = '완료율';
  static String monthlyStatsRateValue(int percent) => '$percent%';
  static String monthlyStatsFraction(int done, int total) => '$done / $total';
  static const monthlyStatsTodoSection = '할 일';
  static const monthlyStatsJobSection = '지원서';
  static const monthlyStatsRoundsLabel = '전형 일정';
  static const monthlyStatsCompaniesLabel = '지원서';
  static const monthlyStatsCoverLettersLabel = '자기소개서';
  static const monthlyStatsPassedLabel = '합격';
  static const monthlyStatsFinalPassedLabel = '최종합격';
  static const monthlyStatsRejectedLabel = '탈락';
  static const monthlyStatsInProgressLabel = '진행중';
  static const monthlyStatsRoundTypeSection = '전형 종류';
  static const monthlyStatsCategorySection = '카테고리';
  static const monthlyStatsBusyDaySection = '가장 바빴던 날';
  static String monthlyStatsBusyDayCount(int count) => '$count개';
  static const monthlyStatsDiarySection = '일기';
  static const monthlyStatsDiaryCountLabel = '일기';
  static const monthlyStatsDiaryDaysLabel = '쓴 날';
  static const monthlyStatsDiaryPhotosLabel = '사진';
  static String monthlyStatsDiaryCount(int count) => '일기 $count개';
  static String monthlyStatsDiaryDaysValue(int count) => '$count일';
  static const monthlyStatsDiaryWroteTail = '를 썼어요';
  static const monthlyStatsLedgerSection = '가계부';
  static const monthlyStatsLedgerCountLabel = '내역';
  static String monthlyStatsLedgerCount(int count) => '내역 $count개';
  static const monthlyStatsPreviewSummary = '지난달 요약';
  static const weeklyStatsPreviewSummary = '지난주 요약';
  static const completeAll = '모두 완료';
  static const postpone = '미루기';
  static const calendarShowTodos = '할일 보기';
  static const calendarShowCompanies = '지원서 보기';
  static const calendarShowLedgerTitle = '내역 보기';
  static const calendarShowLedgerAmount = '금액 보기';
  static const calendarShowLedgerKind = '유형 보기';
  static const calendarShowLedgerMonthStats = '월 통계';
  static const calendarVisibleItems = '캘린더에 표시할 항목';
  static const jobVisibleItems = '지원서에 표시할 항목';
  static const jobShowRejected = '탈락한 지원서';
  static String jobRejectedCalendarToast(String name) =>
      '$name의 일정이 더 이상 캘린더에 나오지 않아요';
  static const calendarSortMode = '정렬 방식';
  static const calendarDiaryMode = '일기 전환';
  static const calendarLedgerMode = '가계부 전환';
  static const calendarSearchHint = '할 일, 지원서, 카테고리 검색';
  static const calendarSearchHintDaily = '할 일, 카테고리 검색';
  static const calendarDiarySearchHint = '제목, 내용 검색';
  static const calendarLedgerSearchHint = '내역, 금액, 카테고리 검색';
  static const ledgerExpense = '수입';
  static const ledgerConsumption = '소비';
  static const ledgerHourly = '시급';
  static const ledgerSalary = '월급';
  static const ledgerPay = '급여';
  static const ledgerTitleHint = '내역을 입력하세요';
  static const ledgerWorkplaceHint = '근무지를 입력하세요';
  static const ledgerAmountHint = '금액을 입력하세요';
  static const ledgerHourlyHint = '시급을 입력하세요';
  static const ledgerMonthlyHint = '월급을 입력하세요';
  static const ledgerAmountSuffix = '원';
  static const ledgerWageHourly = '시급';
  static const ledgerWageMonthly = '월급';
  static const ledgerPaySameDay = '당일';
  static const ledgerPayWeekly = '일주일';
  static const ledgerPayBiweekly = '2주';
  static const ledgerPayMonthly = '한 달';
  static const ledgerPayTwiceMonthly = '한 달에 2번';
  static const ledgerPayTwiceMonthlyShort = '월 2회';
  static const ledgerPayLastDay = '말일';
  static String ledgerMonthDay(int day) =>
      day <= 0 ? ledgerPayLastDay : '$day일';
  static const ledgerPayCycleLabel = '급여일';
  static const ledgerSalaryRepeatHint = '고른 날부터 1년 동안 캘린더에 나와요';
  static const ledgerPayByWeekday = '요일';
  static const ledgerPayWeekFirst = '첫째 주';
  static const ledgerPayWeekSecond = '둘째 주';
  static const ledgerPayWeekThird = '셋째 주';
  static const ledgerPayWeekFourth = '넷째 주';
  static const ledgerPayWeekLast = '마지막 주';
  static const ledgerPayDayFirst = '첫 지급일';
  static const ledgerPayDaySecond = '둘째 지급일';
  static const ledgerWageTypeLabel = '급여';
  static const ledgerWorkLabel = '근무';
  static const ledgerBreak = '휴게';
  static const ledgerBreakNone = '없음';
  static String ledgerBreakMinutes(int minutes) => '$minutes분';
  static const ledgerDeductionLabel = '공제';
  static const ledgerDeductionHelpNet =
      '휴게를 뺀 근무시간에 시급을 곱하고, 고른 보험과 세금을 뺀 금액이 실수령이에요';
  static const ledgerDeductionHelpAll =
      '4대보험은 국민연금 4.75%, 건강보험 3.595%, 장기요양(건보의 13.14%), 고용보험 0.9%가 총액에서 빠져요';
  static const ledgerDeductionHelpEmployment = '고용보험만 고르면 총액의 0.9%만 빠져요';
  static const ledgerDeductionHelpTax = '세금을 켜면 총액의 3.3%가 빠져요';
  static const ledgerDeductionHelpHoliday =
      '주휴수당은 시급×8시간×(일한 시간÷40시간)이 더해져요\n실제 명세서와 조금 차이날 수 있어요';
  static const ledgerDeductionHelpHourlySample = '시급 1만 원 · 8시간';
  static const ledgerTax = '세금';
  static const ledgerInsuranceNone = '없음';
  static const ledgerInsuranceEmployment = '고용보험';
  static const ledgerInsuranceAll = '4대보험';
  static const ledgerWeeklyHoliday = '주휴수당';
  static const ledgerWorkTime = '근무시간';
  static const ledgerBasePay = '기본급';
  static const ledgerHolidayPay = '주휴';
  static const ledgerPension = '국민연금';
  static const ledgerHealth = '건강보험';
  static const ledgerLongTermCare = '장기요양';
  static const ledgerEmploymentInsurance = '고용보험';
  static const ledgerNetPay = '실수령';
  static const missingLedgerBody = '내역, 금액, 날짜, 카테고리는 필수사항이에요!';
  static const missingLedgerSalaryBody = '근무지, 시급, 근무시간, 카테고리는 필수사항이에요!';
  static const missingLedgerSalaryMonthlyBody = '근무지, 월급, 카테고리는 필수사항이에요!';
  static const deleteLedgerBody = '내역이 사라져요';
  static const deleteLedgerRepeatBody = '1년 동안 나오는 급여도 같이 사라져요';
  static const addLedger = '+ 내역을 추가하세요';
  static const ledgerEmptyDay = '이날 내역이 없어요';
  static const ledgerNet = '합계';
  static String ledgerMonthStatsTitle(int month) => '$month월 통계';
  static String ledgerMonthStatsTitleWithYear(int year, int month) =>
      '$year년 $month월 통계';
  static const ledgerTopConsumptionDay = '가장 많이 쓴 날';
  static const ledgerTopIncomeDay = '가장 많이 번 날';
  static String ledgerStatsDayLabel(DateTime date) {
    final weekday = weekdays[date.weekday % 7];
    return '${date.month}. ${date.day}. ($weekday)';
  }
  static const calendarSearchLabel = '검색';
  static const diaryTitleHint = '제목을 입력하세요';
  static const diaryBodyHint = '내용을 입력하세요';
  static const diaryPhotoHint = '사진이나 그림을 넣어 보세요';
  static const diaryPhotoPick = '사진';
  static const diaryPhotoDraw = '그림';
  static const diaryPhotoChange = '바꾸기';
  static const diaryPhotoDrawOn = '그리기';
  static const diaryDrawEdit = '수정하기';
  static const diaryDrawTitle = '그림';
  static const diaryDrawUndo = '되돌리기';
  static const diaryDrawRedo = '다시 실행';
  static const diaryDrawClear = '모두 지우기';
  static const diaryDrawPen = '펜';
  static const diaryDrawBrush = '브러시';
  static const diaryDrawCrayon = '크레용';
  static const diaryDrawCalligraphy = '붓글씨';
  static const diaryDrawWatercolor = '수채화';
  static const diaryDrawPencil = '연필';
  static const diaryDrawMarker = '마커';
  static const diaryDrawHighlighter = '형광펜';
  static const diaryDrawChalk = '분필';
  static const diaryDrawSpray = '스프레이';
  static const diaryDrawLine = '선';
  static const diaryDrawRect = '네모';
  static const diaryDrawOval = '원';
  static const diaryDrawFill = '채우기';
  static const diaryDrawEraser = '지우개';
  static const diaryDrawZoomIn = '확대';
  static const diaryDrawZoomOut = '축소';
  static const diaryDrawZoomPanHint = '두 손가락으로 드래그하면 화면을 옮길 수 있어요';
  static const diaryDrawZoomPanHintPc = '드래그하면 화면을 옮길 수 있어요';
  static const diaryFallback = '일기';
  static const diaryCoverBasic = '기본';
  static const diaryCoverLined = '줄노트';
  static const diaryCoverGrid = '모눈';
  static const diaryCoverDotted = '점노트';
  static const diaryCoverKraft = '크라프트';
  static const diaryCoverSky = '하늘';
  static const diaryCoverRose = '복숭아';
  static const diaryCoverMint = '민트';
  static const diaryCoverBlank = '무지';
  static const missingDiaryBody = '제목, 날짜, 카테고리는 필수사항이에요!';
  static const deleteDiaryBody = '일기가 사라져요';
  static const deleteDiaryPhotoTitle = '사진을 삭제하시나요?';
  static const deleteDiaryPhotoBody = '사진이 사라져요';
  static const addEvent = '+ 할 일을 추가하세요';
  static const eventTitleHint = '할 일을 입력하세요';
  static const eventMemoHint = '메모를 입력하세요';
  static const missingEventBody = '할 일, 날짜, 카테고리는 필수사항이에요!';
  static const categoryAction = '카테고리';
  static const addCategory = '추가';
  static const edit = '편집';
  static const modify = '수정';
  static const done = '완료';
  static const categoryEditTitle = '카테고리 편집';
  static const deleteSelectedCategoriesBody = '선택한 카테고리들이 사라져요';
  static const editOneCategoryTitle = '수정은 하나만 가능해요';
  static const editOneCategoryBody = '카테고리를 하나만 선택해 주세요';
  static const addCategoryTitle = '카테고리 추가';
  static const categoryColorInUse = '사용 중인 색';
  static const categoryNameHint = '카테고리명을 입력하세요';
  static const missingCategoryBody = '카테고리명은 필수사항이에요!';
  static const dateAction = '날짜';
  static const memoAction = '메모';
  static const emojiAction = '스티커';
  static const emojiClear = '스티커 떼어내기';
  static const roundAction = '전형';
  static const timeAction = '시간';
  static const timeSortView = '시간 순으로 보기';
  static const timeDisplay = '시간 표시';
  static const timeHour24 = '24시간으로 표시';
  static const parseTitleTime = '자동 시간 입력';
  static const timeSortLockTitle = '순서를 바꿀 수 없어요';
  static const timeSortLockBody = '시간 순으로 보기가 켜져 있어요!';
  static const dateSortAction = '날짜순 정리';
  static const dateSortLockBody = '날짜 순으로 보기가 켜져 있어요!';
  static const rejectedReorderLockBody = '탈락한 지원서는 순서를 바꿀 수 없어요';
  static const timeStartLabel = '시작';
  static const timeEndLabel = '종료';
  static const timeEndEmpty = '없음';
  static const timeClear = '시간 초기화';
  static const timeOrderInvalid = '종료 시간이 시작 시간보다 빠를 수 없어요!';
  static const allDayLabel = '하루 종일';
  static const allDayShort = '종일';
  static const amLabel = '오전';
  static const pmLabel = '오후';
  static const calendarModeSingle = '일반';
  static const calendarModeRange = '기간';
  static const calendarModeRepeat = '반복';
  static const calendarModeMultiple = '다중';
  static const rangeEventLabel = '기간 일정';
  static const rangeDiaryLabel = '기간 일기';
  static const multipleEventLabel = '다중 일정';
  static const repeatEventLabel = '반복 일정';
  static const repeatTypeLabel = '반복 유형';
  static const repeatStartLabel = '시작 날짜';
  static const repeatEndLabel = '종료 날짜';
  static const repeatEndNone = '없음';
  static const repeatKindWeekly = '매주';
  static const repeatKindMonthly = '매월';
  static const repeatKindYearly = '매년';
  static const repeatMonthByDate = '날짜';
  static const repeatMonthByWeekday = '요일';
  static const deleteRepeatTitle = '반복 일정을 삭제하시겠습니까?';
  static const deleteRepeatThis = '이 일정만 삭제';
  static const deleteRepeatFollowing = '이후 일정 모두 삭제';
  static const deleteRepeatAll = '전체 반복 일정 삭제';
  static const friendsProfile = '프로필';
  static const friendsProfileSettings = '내 프로필';
  static const friendsCategoryShare = '카테고리 공개';
  static const friendsCategoryShareHint = '친구에게 보여줄 카테고리를 설정해요';
  static const friendsPhotoFailed = '사진을 올리지 못했어요';
  static const friendsPhotoTooBig = '5MB보다 작은 사진을 골라 주세요';
  static const friendsPhotoTitle = '프로필 이미지';
  static const friendsPhotoPick = '바꾸기';
  static const friendsPhotoClear = '삭제';
  static const friendsPhotoClearTitle = '프로필 이미지를 삭제할까요?';
  static const friendsPhotoClearBody = '기본 이미지로 변경돼요';
  static const friendsPhotoCleared = '기본 이미지로 바꿨어요';
  static const friendsAccount = '계정';
  static const friendsMyName = '이름';
  static const friendsMyNameHint = '친구에게 보이는 이름이에요';
  static const friendsNameEditHint = '이름을 입력하세요';
  static const friendsNameChange = '바꾸기';
  static const friendsNameChanged = '이름을 저장했어요';
  static const friendsNameBad = '1~16자로 적어 주세요. #과 @는 쓸 수 없어요';
  static const friendsMyCode = '아이디';
  static const friendsMyCodeHint = '친구를 찾을 때 이 아이디를 알려 주세요';
  static const friendsCodeEditHint = '아이디를 입력하세요';
  static const friendsCopy = '복사';
  static const friendsCopied = '아이디를 복사했어요';
  static const friendsAdd = '친구 추가';
  static const friendsHomeAdd = '친구 추가';
  static const friendsHomeMe = '나';
  static const friendsCodeHint = '상대 아이디를 입력하세요';
  static const friendsCodeRegister = '아이디 만들기';
  static const friendsCodeRegisterHint =
      '친구를 찾을 때 쓰는 아이디예요. 영문 소문자·숫자·밑줄·마침표, 2~32자';
  static const friendsCodeSave = '등록';
  static const friendsCodeChange = '바꾸기';
  static const friendsCodeChanged = '아이디를 저장했어요';
  static const friendsCodeTaken = '이미 쓰는 아이디예요';
  static const friendsCodeBad =
      '영문 소문자, 숫자, _, . 만 2~32자로 써 주세요. .. 는 안 돼요';
  static const friendsCodeNeed = '아이디를 먼저 만들어 주세요';
  static const friendsProfileNeed = '이름과 아이디를 먼저 등록해 주세요';
  static String friendsCodeCooldown(int days) => '$days일 뒤에 바꿀 수 있어요';
  static const friendsSend = '요청 보내기';
  static const friendsIncoming = '받은 친구 요청';
  static const friendsOutgoing = '보낸 친구 요청';
  static const friendsSharedTodo = '같이 할 일';
  static const friendsSharedTodoAdd = '같이 할 일 추가';
  static const friendsSharedTodoIncoming = '받은 같이 할 일 요청';
  static const friendsSharedTodoOutgoing = '보낸 같이 할 일 요청';
  static String friendsSharedTodoSent(String name) =>
      '${name.trim()}님에게 같이 할 일 요청을 보냈어요';
  static const friendsSharedTodoAccepted = '같이 할 일이 생겼어요';
  static const friendsSharedTodoWaiting = '상대도 완료해야 끝나요';
  static const friendsSharedTodoDone = '둘 다 완료했어요';
  static const friendsSharedTodoBad = '할 일을 다시 확인해 주세요';
  static const friendsNotFriends = '친구가 아니에요';
  static const friendsList = '내 친구';
  static const friendsEmpty = '아직 친구가 없어요';
  static const friendsEmptyHint = '아이디를 알려 주고 요청을 보내 보세요';
  static const friendsAccept = '수락';
  static const friendsDecline = '거절';
  static const friendsCancel = '취소';
  static const friendsFavorite = '즐겨찾기';
  static const friendsFavoriteAdded = '즐겨찾기에 추가했어요';
  static const friendsFavoriteRemoved = '즐겨찾기에서 해제했어요';
  static const friendsHomePin = '홈 화면에 추가';
  static const friendsHomeUnpin = '홈 화면에서 삭제';
  static String friendsHomePinned(String name) =>
      '${name.trim()}님을 홈 화면에 추가했어요';
  static String friendsHomeUnpinned(String name) =>
      '${name.trim()}님을 홈 화면에서 삭제했어요';
  static const friendsRemove = '친구 끊기';
  static String friendsUnfriended(String name) =>
      '${name.trim()}님과 친구를 끊었어요';
  static const friendsRemoveTitle = '친구를 끊을까요?';
  static const friendsRemoveBody = '상대도 내 일정을 볼 수 없어요';
  static const friendsNeedLogin = '로그인하면 친구를 추가할 수 있어요';
  static const friendsNotFound = '이 아이디로 친구를 찾지 못했어요';
  static const friendsSelf = '내 아이디예요';
  static const friendsAlready = '이미 친구예요';
  static const friendsAlreadySent = '이미 친구 요청을 보냈어요';
  static String friendsSent(String name) =>
      '${name.trim()}님에게 친구 요청을 보냈어요';
  static const friendsAccepted = '친구가 되었어요';
  static const friendsRateLimited = '잠시 후 다시 시도해 주세요';
  static const friendsFailed = '잠시 후 다시 시도해 주세요';
  static const friendsCalendarDenied = '친구 일정을 볼 수 없어요';
  static const friendsBusyLabel = '바쁨';
  static String friendsRequestCount(int count) => '요청 $count';
}
