class AppStrings {
  AppStrings._();

  static const appName = '잡플래너';
  static const jobGreeting = '오늘도 한 걸음 더';
  static const jobSubtitle = '취업 과정을 한곳에서 관리하세요';
  static const compactView = '간략히 보기';
  static const detailedView = '자세히 보기';
  static const defaultView = '기본보기';
  static const categoryView = '카테고리별 보기';
  static const settingsTitle = '설정';
  static const settingsHomeSection = '홈 화면';
  static const settingsHomeLayoutSection = '홈 화면 설정';
  static const homeShowLeftover = '미완료 할 일';
  static const homeShowToday = '오늘';
  static const homeShowTomorrow = '내일';
  static const homeShowWeek = '일주일';
  static const homeShowMonth = '이번 달';
  static const settingsTodoSection = '할 일';
  static const settingsAppearanceSection = '화면 모드';
  static const lightMode = '라이트 모드';
  static const darkMode = '다크 모드';
  static const settingsNotificationSection = '알림 설정';
  static const todoNotificationSetting = '할 일 알림 설정';
  static const summaryNotificationSetting = '요약 알림 설정';
  static const notifyOff = '사용 안함';
  static const notifyMinutes5 = '5분 전';
  static const notifyMinutes10 = '10분 전';
  static const notifyMinutes30 = '30분 전';
  static const notifyHours1 = '1시간 전';
  static const todoReminderChannelName = '할 일 알림';
  static const todoReminderChannelDescription = '시간이 있는 할 일을 미리 알려줘요';
  static const summaryReminderChannelName = '요약 알림';
  static const summaryReminderChannelDescription = '하루 일정을 모아서 알려줘요';
  static String todoReminderHint(String leadLabel) =>
      '시간이 설정된 할 일이 $leadLabel에 알림으로 와요';
  static String todoReminderBody(int leadMinutes) => leadMinutes % 60 == 0
      ? '${leadMinutes ~/ 60}시간 후 시작해요'
      : '$leadMinutes분 후 시작해요';
  static String summaryTimeLabel(int minutes) {
    final hour = minutes ~/ 60;
    final minute = minutes % 60;
    final period = hour < 12 ? amLabel : pmLabel;
    final hour12 = hour % 12 == 0 ? 12 : hour % 12;
    return '$period $hour12:${minute.toString().padLeft(2, '0')}';
  }

  static String summaryReminderHint(int minutes) =>
      '매일 ${summaryTimeLabel(minutes)}에 오늘 일정을 알려줘요';
  static String summaryNotificationTitle(int count) =>
      count == 0 ? '오늘의 일정' : '오늘의 일정 $count개';
  static const summaryNotificationEmpty = '오늘 일정이 없어요';
  static const companySection = '기업';
  static const jobScreenTitle = '기업관리';
  static const searchHint = '기업명, 직무 검색';
  static const homeSearchHint = '할 일, 기업, 카테고리 검색';
  static const addCompany = '+ 기업을 추가하세요';
  static const addCompanyTitle = '기업 추가';
  static const save = '저장';
  static const missingFieldsTitle = '무언가 빠뜨렸어요 😭';
  static const missingFieldsBody = '기업명과 직무는 필수사항이에요!';
  static const confirm = '확인했어요';
  static const deleteTitle = '정말 삭제할까요?';
  static const deleteBody = '정보가 사라져요';
  static const deleteEventBody = '일정이 사라져요';
  static const deleteCompanyBody = '기업이 사라져요';
  static const deleteCoverLetterTitle = '자소서를 삭제하시나요?';
  static const deleteCoverLetterBody = '파일이 사라져요';
  static const cancel = '취소';
  static const delete = '삭제';
  static const companyNameHint = '기업명을 입력하세요';
  static const colCompany = '기업명';
  static const colApplyStatus = '지원상태';
  static const colPosition = '직무';
  static const positionHint = '직무를 입력하세요';
  static String roundLabel(int number) => '$number차';
  static const roundStageNameHint = '전형을 입력하세요';
  static const roundDateHint = '날짜를 입력하세요';
  static const roundNoteHint = '추가정보를 입력하세요';
  static const emptyValue = '—';
  static const colCoverLetter = '자기소개서';
  static const attachFile = '파일 첨부';
  static const coverLetterNotFound = '자기소개서 파일을 찾을 수 없어요';
  static const coverLetterOpenFailed = '파일을 열 수 없어요';
  static const monthSuffix = '월';
  static const yearSuffix = '년';
  static const daySuffix = '일';
  static const weekdays = ['일', '월', '화', '수', '목', '금', '토'];
  static const todayTitle = '오늘';
  static const tomorrowTitle = '내일';
  static const dayAfterTomorrowTitle = '모레';
  static const weekTitle = '일주일';
  static const monthTitle = '이번 달';
  static String leftoverTodos(int count) => '$count개의 남은 할 일';
  static const leftoverHeadline = '완료하지 않은 할 일이';
  static String leftoverCount(int count) => '$count개';
  static const leftoverExists = '있습니다';
  static const completeAll = '모두 완료';
  static const calendarShowTodos = '할일 보기';
  static const calendarShowCompanies = '기업 보기';
  static const calendarVisibleItems = '캘린더에 표시할 항목';
  static const calendarSortMode = '정렬 방식';
  static const addEvent = '+ 할 일을 추가하세요';
  static const eventTitleHint = '할 일을 입력하세요';
  static const eventMemoHint = '메모를 입력하세요';
  static const missingEventBody = '할 일, 날짜, 카테고리는 필수사항이에요!';
  static const categoryAction = '카테고리';
  static const addCategory = '추가';
  static const edit = '편집';
  static const modify = '수정';
  static const done = '완료';
  static const categoryEditTitle = '카테고리 편집';
  static const deleteSelectedCategoriesBody = '선택한 카테고리들이 사라져요';
  static const editOneCategoryTitle = '수정은 하나만 가능해요';
  static const editOneCategoryBody = '카테고리를 하나만 선택해 주세요';
  static const addCategoryTitle = '카테고리 추가';
  static const categoryNameHint = '카테고리명을 입력하세요';
  static const missingCategoryBody = '카테고리명은 필수사항이에요!';
  static const dateAction = '날짜';
  static const memoAction = '메모';
  static const timeAction = '시간';
  static const timeSortView = '시간 순으로 보기';
  static const timeDisplay = '시간 표시';
  static const timeSortLockTitle = '순서를 바꿀 수 없어요';
  static const timeSortLockBody = '시간 순으로 보기가 켜져 있어요!';
  static const dateSortAction = '날짜순 정리';
  static const dateSortLockBody = '날짜 순으로 보기가 켜져 있어요!';
  static const rejectedReorderLockBody = '탈락한 기업은 순서를 바꿀 수 없어요';
  static const timeStartLabel = '시작';
  static const timeEndLabel = '종료';
  static const timeClear = '시간 초기화';
  static const timeOrderInvalid = '종료 시간이 시작 시간보다 빠를 수 없어요!';
  static const allDayLabel = '하루 종일';
  static const amLabel = '오전';
  static const pmLabel = '오후';
  static const calendarModeSingle = '일반';
  static const calendarModeRange = '기간';
  static const calendarModeRepeat = '반복';
  static const calendarModeMultiple = '다중';
  static const rangeEventLabel = '기간 일정';
  static const multipleEventLabel = '다중 일정';
  static const repeatEventLabel = '반복 일정';
  static const repeatTypeLabel = '반복 유형';
  static const repeatStartLabel = '시작 날짜';
  static const repeatEndLabel = '종료 날짜';
  static const repeatEndNone = '없음';
  static const repeatKindWeekly = '매주';
  static const repeatKindMonthly = '매월';
  static const repeatKindYearly = '매년';
  static const deleteRepeatTitle = '반복 일정을 삭제하시겠습니까?';
  static const deleteRepeatThis = '이 일정만 삭제';
  static const deleteRepeatFollowing = '이후 일정 모두 삭제';
  static const deleteRepeatAll = '전체 반복 일정 삭제';
}
